export * from "./db.controler"
export * from "./grade.controller"
export * from "./project.controller"
export * from "./chapter.controler"
export * from "./gradingParameters.controller"
export * from "./subAspect.controller"